using Cirq.Core.Digital;
using Cirq.Core.Simulation;
using Cirq.Core.Units;
using CommunityToolkit.Mvvm.ComponentModel;

namespace Cirq.Components.Buses;

/// <summary>
/// An I²C master that plays a written-out list of transactions.
/// <para>
/// There is no processor here to run a driver, so the transactions are the script: each line is
/// either <c>w &lt;address&gt; &lt;byte&gt;...</c> to write or <c>r &lt;address&gt;
/// &lt;count&gt;</c> to read, all in hex, separated by semicolons or newlines. A seven-bit
/// address is written as itself — <c>50</c>, not <c>A0</c> — and the read/write bit is added here,
/// which is the opposite of the confusion most datasheets cause.
/// </para>
/// <para>
/// The whole waveform is worked out in advance and then played, rather than being generated by a
/// state machine reacting to the bus. That makes the edges exact and the runs repeatable, and it
/// means the clock is genuinely the frequency you asked for. The cost is that it does not stop
/// early when a device fails to acknowledge — it records what happened instead, which is what
/// <see cref="LastTransferAcknowledged"/> is for.
/// </para>
/// </summary>
public sealed partial class I2cMaster : I2cDevice, IBreakpointSource
{
    /// <summary>What to do with SDA at a given moment, and whether to look at it.</summary>
    private readonly record struct Step(double Time, bool SclLow, bool SdaLow, Sampling Sample);

    private enum Sampling { None, Acknowledge, ReadBit }

    private List<Step> _schedule = [];
    private int _next;
    private string _compiledFrom = string.Empty;

    private int _readBits;
    private int _readValue;

    public I2cMaster()
    {
        PropagationDelay = 50e-9;
        ConfigurePins([], [Sda, Scl]);
        Terminals = [Vcc, Sda, Gnd, Scl];
    }

    /// <summary>
    /// The transactions to run, once, from the start of the simulation. Hex throughout.
    /// <code>
    /// w 50 00 00 48 49 3B      ; write 48 49 3B to address 0x50 at offset 0x0000
    /// r 50 4                   ; read four bytes back
    /// </code>
    /// </summary>
    [ObservableProperty]
    public partial string Transactions { get; set; } = "w 50 00 00 48 49; r 50 2";

    /// <summary>Bus clock, in hertz. 100 kHz is standard mode; 400 kHz is fast mode.</summary>
    [ObservableProperty]
    public partial double ClockFrequency { get; set; } = 100e3;

    /// <summary>How long to wait before starting, in seconds.</summary>
    [ObservableProperty]
    public partial double StartDelay { get; set; } = 100e-6;

    public override string ComponentType => "I2C Master";

    public override string ValueLabel => SiPrefix.Format(ClockFrequency, "Hz");

    /// <summary>Bytes read back, in the order they arrived.</summary>
    public List<int> ReceivedBytes { get; } = [];

    /// <summary>
    /// Whether every byte sent so far was acknowledged. A device that is absent, or addressed
    /// wrongly, leaves the line high and this goes false — which is the only symptom you get.
    /// </summary>
    public bool LastTransferAcknowledged { get; private set; } = true;

    /// <summary>True once the whole script has been played.</summary>
    public bool IsFinished => _schedule.Count > 0 && _next >= _schedule.Count;

    public override void EvaluateLogic(IDigitalContext context)
    {
        Compile();

        var delay = DelayFor(context);

        // Nothing scheduled yet, or all done: let go of both lines, which is what idle means.
        if (_next >= _schedule.Count)
        {
            Drive(context, 0, false);
            Drive(context, 1, false);
            return;
        }

        while (_next < _schedule.Count && _schedule[_next].Time <= context.Time)
        {
            var step = _schedule[_next];

            switch (step.Sample)
            {
                case Sampling.Acknowledge:
                    // A device acknowledges by pulling the line down during the ninth clock.
                    if (IsHigh(context, Sda)) LastTransferAcknowledged = false;
                    break;

                case Sampling.ReadBit:
                    _readValue = (_readValue << 1) | (IsHigh(context, Sda) ? 1 : 0);
                    if (++_readBits == 8)
                    {
                        ReceivedBytes.Add(_readValue);
                        _readBits = 0;
                        _readValue = 0;
                    }
                    break;
            }

            _next++;
        }

        var current = _schedule[Math.Min(_next, _schedule.Count - 1)];
        var applied = _next == 0 ? new Step(0, false, false, Sampling.None) : _schedule[_next - 1];

        Drive(context, 0, applied.SdaLow);
        Drive(context, 1, applied.SclLow);
    }

    /// <summary>The next moment the waveform changes, so edges land where they belong.</summary>
    public double? NextBreakpointAfter(double time)
    {
        Compile();

        foreach (var step in _schedule)
            if (step.Time > time) return step.Time;

        return null;
    }

    /// <summary>Turns the script into a list of line states with times against them.</summary>
    private void Compile()
    {
        if (_compiledFrom == Transactions && _schedule.Count > 0) return;

        _compiledFrom = Transactions;
        _schedule = [];

        var bit = 1.0 / Math.Max(ClockFrequency, 1.0);
        var half = bit / 2.0;
        var quarter = bit / 4.0;

        var t = Math.Max(StartDelay, 0.0);

        void At(double time, bool sclLow, bool sdaLow, Sampling sample = Sampling.None) =>
            _schedule.Add(new Step(time, sclLow, sdaLow, sample));

        // One bit: set the data while the clock is low, then raise the clock over it.
        void SendBit(bool high, Sampling sample = Sampling.None)
        {
            At(t, true, !high);
            At(t + half, false, !high, sample);
            t += bit;
        }

        foreach (var line in Transactions.Split([';', '\n', '\r'], StringSplitOptions.RemoveEmptyEntries))
        {
            var parts = line.Trim().Split(' ', StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length < 2) continue;

            var reading = parts[0].StartsWith('r');
            if (!reading && !parts[0].StartsWith('w')) continue;

            if (!TryHex(parts[1], out var address)) continue;

            // Start: the data line falls while the clock is still high. Nothing else on the bus
            // does that, which is how every device knows a transfer is beginning.
            At(t, false, false);
            At(t + quarter, false, true);
            t += half;

            for (var i = 6; i >= 0; i--) SendBit((address & (1 << i)) != 0);
            SendBit(reading);
            SendBit(true, Sampling.Acknowledge);            // released, for the device to pull down

            if (reading)
            {
                var count = TryHex(parts[2], out var n) ? n : 1;

                for (var b = 0; b < count; b++)
                {
                    for (var i = 0; i < 8; i++) SendBit(true, Sampling.ReadBit);

                    // Acknowledge every byte but the last, which is how a device is told to stop.
                    SendBit(b == count - 1);
                }
            }
            else
            {
                foreach (var token in parts.Skip(2))
                {
                    if (!TryHex(token, out var value)) continue;

                    for (var i = 7; i >= 0; i--) SendBit((value & (1 << i)) != 0);
                    SendBit(true, Sampling.Acknowledge);
                }
            }

            // Stop: the clock goes high first, then the data line rises under it.
            At(t, true, true);
            At(t + quarter, false, true);
            At(t + half, false, false);
            t += bit;
        }
    }

    private static bool TryHex(string token, out int value) =>
        int.TryParse(token.Trim(), System.Globalization.NumberStyles.HexNumber, null, out value);

    public override void ResetLogic()
    {
        base.ResetLogic();

        _next = 0;
        _readBits = 0;
        _readValue = 0;
        _schedule = [];
        _compiledFrom = string.Empty;
        ReceivedBytes.Clear();
        LastTransferAcknowledged = true;
    }

    partial void OnTransactionsChanged(string value) => NotifyValueChanged();
}
