<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Cirq.Cli/Cirq.Cli.csproj" />
    <ProjectReference Include="../../src/Cirq.Core/Cirq.Core.csproj" />
    <ProjectReference Include="../../src/Cirq.Engine/Cirq.Engine.csproj" />
    <ProjectReference Include="../../src/Cirq.Components/Cirq.Components.csproj" />
  </ItemGroup>
</Project>
